spring:
  cloud:
    stream:
      binders:
        local_kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:29092
                      zkNodes: localhost:2181
      bindings:
        input:
          binder: local_kafka
          destination: queue.messaging.person
          group: testing
          content-type: application/json


