spring:
  cloud:
    stream:
      binders:
        local_kafka:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:29092
                      zkNodes: localhost:2181
      bindings:
        output:
          binder: local_kafka
          destination: queue.messaging.name
          group: testing
          content-type: text/plain



